### ISSUE TITLE
avro-ts: Include schema in output

### ISSUE THREAD

**Issue by epbensimpson** [ovotech/castle#130]
We're using KafkaJS Schema Registry to decode avro messages. It would be nice if avro-ts included the schema used to generate the types so we can decode to the appropriate version of the schema. e.g.

```ts
// without schema, have to be explicit about version if the consumer wants a different version from the producer
const registryId = await registry.getRegistryId(MyEvents.MyEventName, schemaVersion);
const schema = await registry.getSchema(registryId);
const decoded = await registry.decode(buffer, { AVRO: { readerSchema: schema } });

// with schema
const decoded = await registry.decode(buffer, { AVRO: { readerSchema: MyEvents.MyEventSchema } });
```

The `Schema` type generated could be equivalent to the following interface:

```ts
export interface RawAvroSchema {
    name: string;
    namespace?: string;
    type: 'record';
    fields: any[];
}
```

This would also be handy for registering the schema with Schema Registry in the first place if you were publishing using generated types.

Generators for other languages such as the .NET `apache.avro.tools` package do this and it's really helpful.

**Comment by AlexeyRaga** [comment]
I believe that internally `avro-ts` already has a value of `Schema` from `avsc` package, it'd be great to get a reference to it as a part of a message interface or/and as a static field, similarly to how we get the qualified name now.

**Comment by ivank** [comment]
Can't you already include your schema as a json? What we do is just import it into using typescript's import json feature and use it directly.

**Comment by epbensimpson** [comment]
It's pretty inconvenient when working with an avro file containing multiple types.

```json
[
  {
    "name": "Foo",
    "namespace": "Events",
    "type": "record",
    "fields": [
      {
        "name": "field1",
        "type": "string"
      }
    ]
  },
  {
    "name": "Bar",
    "namespace": "Events",
    "type": "record",
    "fields": [
      {
        "name": "field1",
        "type": "string"
      }
    ]
  }
]
```

In order to reference the schema for `Events.Foo` by importing that directly, I now have to do additional work. But if codegen handled this, I could just use `Events.FooSchema` exactly the same as I can currently use `Events.FooName` to reference its name.

**Comment by AlexeyRaga** [comment]
Yes, what @epbensimpson said.
Plus, with multiple types in play, importing schemas separately is inconvenient because there is no link between a type and its schema.
But if the type interface would include a function that returns the schema then the ambiguity would be solved and we would always know what type has what schema.

**Comment by ivank** [comment]
Fair enough, it does sound quite useful! I'll look into this, but any PRs are welcome!

**Comment by AlexeyRaga** [comment]
@ivank Please have a look at #139 and give us your feedback!

**Comment by AlexeyRaga** [comment]
@ivank Versions have been bumped. Please advise if there is anything else that we can do.
