### ISSUE TITLE
Support multiple schemas in one topic

### ISSUE THREAD

**Issue by tzachshabtay** [ovotech/castle#27]
The code currently makes the wrong assumption that there can be only a single schema in a topic, see here: https://github.com/ovotech/castle/blob/6210727239c7ca98ccd37848e40e9975c4bcb22d/packages/avro-kafkajs/src/SchemaRegistry.ts#L94

This makes it impossible to produce messages of multiple schemas in a single topic.

**Comment by ivank** [comment]
Hum ok never thought it was possible, care to point me to a doc example, I'll be more the happy to plug in the edge cases.

**Comment by tzachshabtay** [comment]
I don't know of an example, it's just never stated that there should only be a single event type in a topic. Subject to topic is a many to many relationship (you can have multiple subjects in a topic, and you can have the same subject in multiple topics). Kafka-avro for example solved it with a configurable strategy for selecting the subject name: https://github.com/waldophotos/kafka-avro/blob/master/README.md#support-for-several-event-types-in-the-same-topic

**Comment by tzachshabtay** [comment]
> While you can have multiple different schemas per topic for sure, can you actually have multiple schemas _per message_ ?

Not sure if that's related to the issue, however: technically I'd say it's possible, but not sure how you can support that, and the workaround is simple as you can write a schema that imports other schemas, so you can have multiple records of multiple schemas in a single message, encapsulated in a single schema.

> When you produce you can specify exactly which schema you are using and it would encode it correctly, and when you consume you will get the exact schema for the message you're trying to decode.

> The "type" here is whether its "value" or "key" schema, as each message can have different Avro schemas for both. Am I missing something?

I was specifically testing "values", though I'm guessing the same problem also exists for "keys".

Here's an example:
let's say I have `test1.avsc` with:
```
{
  "type" : "record",
  "name" : "Test1",
  "namespace" : "test",
  "fields" : [ {
    "name" : "long_field",
    "type" : "long"
  }]
}
```

and I also have `test2.avsc` with:
```
{
  "type" : "record",
  "name" : "Test2",
  "namespace" : "test",
  "fields" : [ {
    "name" : "string_field",
    "type" : "string"
  }]
}
```

And now I try to produce both of them to the same topic.
In your codebase, the producer calls schema registry's `encode`, which calls `getDecodeItem`, which calls `schemaToId` with the passed subject, which calls `checkSubjectRegistered` which checks that the subject + schema match what's in schema registry. If it's not found or doesn't match it calls `addSubjectVersion` to add the schema to the subject as a new version.

For the first message `test1` (assuming I haven't already registered in the registry) `checkSubjectRegistered` will return not found, and then `addSubjectVersion` will register the subject + schema for test1.
For the second message `test2`, because you pass the same subject, the schema wouldn't match so `checkSubjectRegistered` will error, and then `addSubjectVersion` would error as well as the two schemas are not compatible (and they're not supposed to be compatible, they're supposed to be 2 different subjects in the schema registry).

**Comment by ivank** [comment]
Yeah gotcha - as far as I can tell it looks like the cache key doesn't hold all the information it needs. I'll see what I can do to fix it, though doing it in a performant way might be tricky ...

**Comment by tzachshabtay** [comment]
The ideal way really is for the user to be able to specify a subject in the produce function (maximum flexibility and negligible performance overhead)

**Comment by ivank** [comment]
I'd love to support schema evolution as is so the user doesn't really need to understand the intricacies of schema registry + Avro + kafka setup. But you're right it might be worth adding an additional method to allow custom selection of the subject.

Can you tell me more about your specific use case? Do you need caching? Do you want it to be symmetric with consumption or do you want it to just produce some topics in a custom schema?

**Comment by ivank** [comment]
I'll merge the PR for now, as I think it fixes the original problem, but if you can give your specific use case in more detail I can reopen this and figure it out from there. Hope that's not too rude :)
