### ISSUE TITLE
avro-ts-cli: Cannot find module 'ansi-regex'

### ISSUE THREAD

**Issue by lajtmaN** [ovotech/castle#30]
It is not possible to run the CLI without manually installing 'ansi-regex'.
This applies both when running through npx or when installing it. 
```
npx @ovotech/avro-ts-cli ./*.avsc --output-dir .\typescript\
npx: installed 12 in 8.231s
Cannot find module 'ansi-regex'
```

**Comment by ivank** [comment]
Thanks a lot for flagging this @lajtmaN
