### ISSUE TITLE
avro-ts: type referenced in other schema file not working properly

### ISSUE THREAD

**Issue by pylebecq** [ovotech/castle#41]
Hello 👋 

Sorry this is going to be a long text but I prefer giving as much information as possible.
I created a small repository to reproduce the issue here: https://github.com/pylebecq/avro-ts-referenced-types-issue

I have a Java application receiving messages (from an Apache Pulsar cluster, but it does not matter). The data expected in those messages is some Avro encoded data. Some of the schema files reference types defined in other schema files, and schema files contain namespaces.
This is supported when using Avro in Java as we have multiple Java application being able to use these schema files properly.

I need a typescript application to be able to send messages to the previously mentioned Java application.
So I'm trying to use this library to generate typescript definitions from the schema files. This way, when there are some schema change, I can get a quick typescript compilation error if something is not correct.

However, when generating the typescript definitions, some namespaces import statement are missing in typescript, resulting in compilation errors:

I'm using these 4 schema files:

<details>
<summary>Message.avsc</summary>

```json
{
  "type": "record",
  "name": "Message",
  "namespace": "my.namespace",
  "fields": [
    {
      "name": "type",
      "type": {
        "type": "enum",
        "name": "MessageType",
        "symbols": ["CreateUser", "UpdateAddress"]
      }
    },
    {
      "name": "CreateUser",
      "type": ["null", "my.namespace.messages.CreateUser"],
      "default": null
    },
    {
      "name": "UpdateAddress",
      "type": ["null", "my.namespace.messages.UpdateAddress"],
      "default": null
    }
  ]
}

```

</details>

<details>
<summary>CreateUser.avsc</summary>

```json
{
  "type": "record",
  "name": "CreateUser",
  "namespace": "my.namespace.messages",
  "fields": [
    {
      "name": "userId",
      "type": "string",
      "logicalType": "uuid"
    },
    {
      "name": "name",
      "type": "string"
    },
    {
      "name": "address",
      "type": "my.namespace.data.Address"
    }
  ]
}
```

</details>

<details>
<summary>UpdateAddress.avsc</summary>

```json
{
  "type": "record",
  "name": "UpdateAddress",
  "namespace": "my.namespace.messages",
  "fields": [
    {
      "name": "userId",
      "type": "string",
      "logicalType": "uuid"
    },
    {
      "name": "address",
      "type": "my.namespace.data.Address"
    }
  ]
}
```

</details>

<details>
<summary>Address.avsc</summary>

```json
{
  "type": "record",
  "name": "Address",
  "namespace": "my.namespace.data",
  "fields": [
    {
      "name": "street",
      "type": "string"
    },
    {
      "name": "zipcode",
      "type": "string"
    },
    {
      "name": "country",
      "type": "string"
    }
  ]
}
```

</details>

If I generated the definitions and try to use them in my project I get these errors during the typescript compilation:

```
yarn run v1.22.4
$ tsc
src/__generated__/CreateUser.avsc.ts(10,18): error TS2503: Cannot find namespace 'MyNamespaceData'.
src/__generated__/CreateUser.avsc.ts(10,18): error TS4033: Property 'address' of exported interface has or is using private name 'MyNamespaceData'.
src/__generated__/Message.avsc.ts(9,28): error TS2503: Cannot find namespace 'MyNamespaceMessages'.
src/__generated__/Message.avsc.ts(9,28): error TS4033: Property 'CreateUser' of exported interface has or is using private name 'MyNamespaceMessages'.
src/__generated__/Message.avsc.ts(10,31): error TS2503: Cannot find namespace 'MyNamespaceMessages'.
src/__generated__/Message.avsc.ts(10,31): error TS4033: Property 'UpdateAddress' of exported interface has or is using private name 'MyNamespaceMessages'.
src/__generated__/UpdateAddress.avsc.ts(9,18): error TS2503: Cannot find namespace 'MyNamespaceData'.
src/__generated__/UpdateAddress.avsc.ts(9,18): error TS4033: Property 'address' of exported interface has or is using private name 'MyNamespaceData'.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

If we take a look at the generated definitions for `CreateUser` for example, we get this:

```typescript
/* eslint-disable @typescript-eslint/no-namespace */

export type CreateUser = MyNamespaceMessages.CreateUser;

export namespace MyNamespaceMessages {
    export const CreateUserName = "my.namespace.messages.CreateUser";
    export interface CreateUser {
        userId: string;
        name: string;
        address: MyNamespaceData.Address;
    }
}
```

So, this file is referencing type `MyNamespaceData.Address` but no import is present in this file, resulting in the `src/__generated__/CreateUser.avsc.ts(10,18): error TS2503: Cannot find namespace 'MyNamespaceData'.` error.

This could be fixed if the generated output contained an import line: `import { MyNamespaceData } from './Address.avsc';`

However, if we take a look at the generated file for `Message`, the issue is even worse:

```typescript
/* eslint-disable @typescript-eslint/no-namespace */

export type Message = MyNamespace.Message;

export namespace MyNamespace {
    export const MessageName = "my.namespace.Message";
    export interface Message {
        type: "CreateUser" | "UpdateAddress";
        CreateUser: null | MyNamespaceMessages.CreateUser;
        UpdateAddress: null | MyNamespaceMessages.UpdateAddress;
    }
}
```

Here, `MyNamespaceMessages` is referenced twice with types in two different files. If we add an import line e.g. `import { MyNamespaceMessages } from './CreateUser.avsc';`, we get another error:

```
src/__generated__/Message.avsc.ts(12,47): error TS2694: Namespace '"/Users/pierre-yves/dev/avro-ts-referenced-types-issue/src/__generated__/CreateUser.avsc".MyNamespaceMessages' has no exported member 'UpdateAddress'.
```

Of course, we cannot simply add a second import line for the namespace referencing the second file, otherwise we get this:

```
src/__generated__/Message.avsc.ts(3,10): error TS2300: Duplicate identifier 'MyNamespaceMessages'.
src/__generated__/Message.avsc.ts(4,10): error TS2300: Duplicate identifier 'MyNamespaceMessages'.
```

If you have any solution to make this work, please let me know.

If there is definitely no workaround this atm, I'm not sure yet about the best way to fix it but here is an idea:
I noticed the types are exported also without the namespace in their name:

```typescript
export type Address = MyNamespaceData.Address;

// [...]
```

If `CreateUser` was referencing the non-namespaced type Address, maybe imports could be easy to generate:

```typescript
/* eslint-disable @typescript-eslint/no-namespace */

import { Address } from "./Address.avsc";

export type CreateUser = MyNamespaceMessages.CreateUser;

export namespace MyNamespaceMessages {
  export const CreateUserName = "my.namespace.messages.CreateUser";
  export interface CreateUser {
    userId: string;
    name: string;
    address: Address;
  }
}
```

And it would also work for the Message type:

```typescript
/* eslint-disable @typescript-eslint/no-namespace */

import { CreateUser } from "./CreateUser.avsc";
import { UpdateAddress } from "./UpdateAddress.avsc";

export type Message = MyNamespace.Message;

export namespace MyNamespace {
  export const MessageName = "my.namespace.Message";
  export interface Message {
    type: "CreateUser" | "UpdateAddress";
    CreateUser: null | CreateUser;
    UpdateAddress: null | UpdateAddress;
  }
}
```

However, this might open some issues of name collisions if there are two different namespaces using a same type name.

**Comment by ivank** [comment]
Thanks for the awesomely outlined issue. Was a pleasure implementing it with so much supporting information.
