### ISSUE TITLE
No Auth support 

### ISSUE THREAD

**Issue by d-sooter** [ovotech/castle#67]
Im trying to use this library along with Confluent cloud and for that auth is needed. 

As far as i can tell you guys dont support any form of auth. Or did i miss something

**Comment by ivank** [comment]
The underlying kafkajs library has quite a wide range of auth options as far as I know.

https://kafka.js.org/docs/configuration#ssl

The castle config just passes that config directly

https://github.com/ovotech/castle/blob/e0a72a74c10a93e0729920e5f23526338b0bb603/packages/castle/src/castle.ts#L74-L77

I really should add some more examples for this!

**Comment by ivank** [comment]
@d-sooter does that work for you, or you needed something different?
