### ISSUE TITLE
Add GetSubjectVersion to schema registry api

### ISSUE THREAD

**Issue by tzachshabtay** [ovotech/castle#74]
Hi, in your current api you have `getSubjectVersionSchema` which maps to `GET /subjects/:subject/versions/:version/schema` but I'm missing a `getSubjectVersion` which maps to `GET /subjects/:subject/versions/:version`, this gets back the schema id (in addition to the schema string) which will be very helpful to me. Thanks.

**Comment by tzachshabtay** [comment]
@ivank thanks for the quick turnaround.
However, there's an issue here, the new endpoint returns schema as a string, and not as a `Schema` like `getSubjectVersionSchema`, can you please fix this (I don't want to call 2 endpoints)?
Thanks.

**Comment by ivank** [comment]
Well that's what the endpoint returns, You should be able to call `JSON.parse` does that work for you?

**Comment by tzachshabtay** [comment]
That works, thanks.
