### ISSUE TITLE
Reduce risks of sending null keys

### ISSUE THREAD

**Issue by Unibozu** [ovotech/castle#77]
Hey Ivan,

Opening a discussion on a recent issue we've at in the BIT team - if you like it I'll open a PR.

We discovered we were producing records without keys due to our limited knowledge of kafka. Kafka brokers block `null` keys on a log-compacted topic but in a way that doesn't immediately fail the production so it didn't show up in the logs for a while.

It's a silly mistake too easy to happen. Strengthening the TS types on castle to make this mistake harder to happen: `CastleSender` can block `undefined` keys, forcing a producer to explicitly define `key: null` in case they want a `null` key.

In essence, this will block `sendFunction(producer, [{value}])` and force to pass a key `sendFunction(producer, [{value, key: null}])`, removing risks of making this mistake again.

```ts
export declare type CastleSender<
  TValue = unknown,
  TKey = AvroMessage['key']
> = (producer: AvroProducer, messages: AvroMessage<TValue, TKey>[]) => Promise<RecordMetadata[]>;
```

into

```ts
export declare type CastleSender<
  TValue = unknown,
  TKey = Exclude<AvroMessage['key'], undefined>
> = (producer: AvroProducer, messages: AvroMessage<TValue, TKey>[]) => Promise<RecordMetadata[]>;
```

Cheers

**Comment by ivank** [comment]
Sounds reasonable, I'll look into it
