### ISSUE TITLE
@ovotech/avro-ts missing dependency @ovotech/ts-compose in npm registry

### ISSUE THREAD

**Issue by konqi** [ovotech/castle#86]
Hi!

my build currently says:
```
error Couldn't find package "@ovotech/ts-compose@^0.16.0" required by "@ovotech/avro-ts" on the "npm" registry.
```

Looks like @ovotech/ts-compose was unpublished from the npm registry.

Is there a workaround or a fix for this?

**Comment by ivank** [comment]
Not sure how that happened, republished it (it was set to private for some reason)

**Comment by konqi** [comment]
Thanks! 😄
