### ISSUE TITLE
is anyone using this with kinesis ?

### ISSUE THREAD

**Issue by mericano1** [ovotech/castle#96]
Hi there, 
more a question than an issue. Do you have anyone using this with AWS Kinesis? Is it compatible as far as you know ? Also could we use it with a JSON schema (and without the schema registry) instead of Avro? Any code examples I could look at ?

Thanks 😉

**Comment by ivank** [comment]
Haven't used AWS kinesis, but I don't really thing they're the same thing. You should check https://kafka.js.org (the underlying library) to figure out if it works with it or not.

As for json schema - no. This was written before https://github.com/kafkajs/confluent-schema-registry and we've made our own little client for castle, but now with this confluent-schema-registry you should be able to consume / produce Kafka with schema registry easily, without the need for castle. They have some examples in their docs https://kafkajs.github.io/confluent-schema-registry/docs/introduction. And the great thing is that they do support json-schema (as well as protobuf I think)

**Comment by mericano1** [comment]
Thanks @ivank. Will ping you if I have other questions 😉
